var fs = require('fs');
var mysql = require('mysql');
var path = require('path');
var $ = require('jquery');
var Bing = require('node-bing-api')({ accKey: 'b7ce17b62cb3407d81318bb1bc5ea63a' });
var sleep = require('sleep');

var schoolNames = ['John Paul the Great Catholic University',
  'Advanced Computing Institute',
  'California Miramar University',
  'West Hills College-Lemoore',
  'Argosy University-The Art Institute of California-Orange County',
  'Bethesda University',
  'Community Christian College',
  'Cambridge Junior College-Yuba City',
  'Los Angeles Film School',
  'Trident University International',
  'Argosy University-The Art Institute of California-Sacramento',
  'Argosy University-San Diego',
  'American River College',
  'California College of the Arts',
  'Contra Costa College',
  'Chapman University',
  'California State University-Fullerton',
  'Diablo Valley College',
  'Coleman University',
  'Columbia College',
  'University of California-Berkeley',
  'University of California-San Diego',
  'University of California-Santa Barbara',
  'Mendocino College',
  'San Jose State University',
  'Sacramento City College',
  'Saddleback College',
  'Solano Community College',
  'Pitzer College',
  'San Diego Mesa College',
  'College of the Redwoods',
  'San Joaquin Valley College-Visalia',
  'Brightwood College-Riverside',
  'Santa Barbara Business College-Ventura',
  'California State University-Stanislaus',
  'California State University-San Bernardino',
  'The California Maritime Academy',
  'Casa Loma College-Van Nuys',
  'El Camino College-Compton Center',
  'Humboldt State University',
  'Loma Linda University',
  'Los Angeles Pierce College',
  'Monterey Peninsula College',
  'Moorpark College',
  'The Master\'s College and Seminary',
  'Notre Dame de Namur University',
  'Occidental College',
  'Loyola Marymount University',
  'Brightwood College-Sacramento',
  'South Baylo University',
  'Santa Rosa Junior College',
  'United Education Institute-Huntington Park Campus',
  'Concorde Career College-San Bernardino',
  'West Valley College',
  'InterCoast Colleges-Orange',
  'Los Angeles ORT College-Los Angeles Campus',
  'Carrington College-San Leandro',
  'Platt College-Los Angeles',
  'East San Gabriel Valley Regional Occupational Program',
  'Argosy University-Orange County',
  'American Career College-Anaheim',
  'American University of Health Sciences',
  'Bakersfield College',
  'California State University-Bakersfield',
  'Le Cordon Bleu College of Culinary Arts-San Francisco',
  'Citrus College',
  'Canada College',
  'California State University-Fresno',
  'University of California-Riverside',
  'Fresno Pacific University',
  'El Camino Community College District',
  'Reedley College',
  'Gavilan College',
  'Glendale Community College',
  'Golden West College',
  'Imperial Valley College',
  'Feather River Community College District',
  'Concorde Career College-North Hollywood',
  'Berkeley City College',
  'Carrington College-Pomona',
  'Azusa Pacific University College',
  'International Professional School of Bodywork',
  'Angeles College',
  'Grace Mission University',
  'DeVry University-California',
  'Advanced Training Associates',
  'United States University',
  'Brightwood College-Fresno',
  'Lincoln University',
  'University of Antelope Valley',
  'California State University-Channel Islands',
  'Epic Bible College',
  'Carrington College-San Jose',
  'Le Cordon Bleu College of Culinary Arts-Pasadena',
  'Argosy University-San Francisco Bay Area',
  'Stanford University',
  'Southern California Institute of Technology',
  'Butte College',
  'California Institute of Integral Studies',
  'California Baptist University',
  'Chaffey College',
  'Empire College',
  'Laney College',
  'Grossmont College',
  'La Sierra University',
  'Irvine Valley College',
  'Middlebury Institute of International Studies at Monterey',
  'Mount Saint Mary\'s University',
  'Los Angeles Mission College',
  'Ohlone College',
  'Mission College',
  'Pacific Union College',
  'College of the Siskiyous',
  'San Jose City College',
  'Skyline College',
  'College of San Mateo',
  'Saint Mary\'s College of California',
  'Samuel Merritt University',
  'Golf Academy of America-Carlsbad',
  'Santa Clara University',
  'Porterville College',
  'Concorde Career College-Garden Grove',
  'University of San Diego',
  'San Francisco Conservatory of Music',
  'Shasta College',
  'Thomas Aquinas College',
  'Copper Mountain Community College',
  'Argosy University-The Art Institute of California-Hollywood',
  'Barstow Community College',
  'Bryan University',
  'Cabrillo College',
  'California Institute of Technology',
  'Concordia University-Irvine',
  'Cuesta College',
  'Foothill College',
  'Southern California Seminary',
  'Pacific States University',
  'Soka University of America',
  'Providence Christian College',
  'Norco College',
  'Moreno Valley College',
  'Allied American University',
  'Touro University Worldwide',
  'Horizon University',
  'West Coast University-Ontario',
  'Advanced College',
  'Argosy University-The Art Institute of California-Silicon Valley',
  'World Mission University',
  'Brightwood College-Bakersfield',
  'Argosy University-Los Angeles',
  'Asher College',
  'Argosy University-The Art Institute of California-Los Angeles',
  'West Coast Ultrasound Institute',
  'Brightwood College-Modesto',
  'Fashion Institute of Design & Merchandising-San Diego',
  'Antioch University-Santa Barbara',
  'Brandman University',
  'Harvey Mudd College',
  'Los Angeles Harbor College',
  'Los Angeles Southwest College',
  'Menlo College',
  'Merced College',
  'Mt San Jacinto Community College District',
  'Mills College',
  'Otis College of Art and Design',
  'Riverside City College',
  'Palo Verde College',
  'San Bernardino Valley College',
  'Santa Barbara Business College-Bakersfield',
  'San Diego City College',
  'Sonoma State University',
  'San Diego Miramar College',
  'San Diego State University',
  'San Francisco Art Institute',
  'Southern California Institute of Architecture',
  'College of the Sequoias',
  'Rio Hondo College',
  'Simpson University',
  'Whittier College',
  'Yeshiva Ohr Elchonon Chabad West Coast Talmudical Seminary',
  'Ventura College',
  'Ashford University',
  'California State Polytechnic University-Pomona',
  'Cuyamaca College',
  'City College of San Francisco',
  'De Anza College',
  'Claremont McKenna College',
  'College of the Desert',
  'California State University-East Bay',
  'Coastline Community College',
  'Dominican University of California',
  'Cerritos College',
  'Columbia College-Hollywood',
  'University of California-Davis',
  'University of California-Santa Cruz',
  'John F. Kennedy University',
  'University of La Verne',
  'Evergreen Valley College',
  'Lake Tahoe Community College',
  'Long Beach City College',
  'Napa Valley College',
  'Palo Alto University',
  'MTI College',
  'Pacific Oaks College',
  'University of the Pacific',
  'Santa Barbara City College',
  'South Coast College',
  'University of Redlands',
  'California Lutheran University',
  'Alliant International University-San Diego',
  'California Christian College',
  'Charles R Drew University of Medicine and Science',
  'California Institute of the Arts',
  'San Diego Christian College',
  'Holy Names University',
  'Humphreys College-Stockton and Modesto Campuses',
  'Lassen Community College',
  'Interior Designers Institute',
  'Hartnell College',
  'Los Angeles Trade Technical College',
  'Merritt College',
  'Los Medanos College',
  'MiraCosta College',
  'National University',
  'Brightwood College-San Diego',
  'College of Marin',
  'William Jessup University',
  'Vanguard University of Southern California',
  'University of Southern California',
  'Sierra College',
  'Westmont College',
  'Woodbury University',
  'Mayfield College',
  'Carrington College-Stockton',
  'Argosy University-Inland Empire',
  'SUM Bible College and Theological Seminary',
  'American Career College-Ontario',
  'Argosy University-The Art Institute of California-Inland Empire',
  'California College San Diego',
  'California University of Management and Sciences',
  'Bergin University of Canine Studies',
  'New York Film Academy',
  'West Coast University-Orange County',
  'Expression College for Digital Arts',
  'Folsom Lake College',
  'Los Angeles College of Music',
  'West Coast University-Los Angeles',
  'Carrington College-Sacramento',
  'Art Center College of Design',
  'California State University-Chico',
  'College of the Canyons',
  'Design Institute of San Diego',
  'California State University-Long Beach',
  'Cogswell College',
  'California State University-Northridge',
  'Cerro Coso Community College',
  'University of California-Irvine',
  'American Jewish University',
  'Life Pacific College',
  'Golden Gate University-San Francisco',
  'Fashion Institute of Design & Merchandising-San Francisco',
  'Fashion Institute of Design & Merchandising-Orange County',
  'Musicians Institute',
  'Santiago Canyon College',
  'Orange Coast College',
  'Hope International University',
  'Newschool of Architecture and Design',
  'Pepperdine University',
  'Platt College-San Diego',
  'Pomona College',
  'San Joaquin Delta College',
  'West Hills College-Coalinga',
  'Pacific College',
  'Pima Medical Institute-Chula Vista',
  'California State University-San Marcos',
  'Fremont College',
  'Antioch University-Los Angeles',
  'Las Positas College',
  'Pacific College of Oriental Medicine-San Diego',
  'California State University-Monterey Bay',
  'Institute of Technology Inc',
  'Platt College-Ontario',
  'Platt College-Riverside',
  'University of Phoenix-California',
  'California College San Diego',
  'Brightwood College-Chula Vista',
  'Unitek College',
  'Academy of Couture Art',
  'Woodland Community College',
  'Brightwood College-Palm Springs',
  'University of California-Merced',
  'Stanbridge College',
  'Carrington College-Citrus Heights',
  'University of the West',
  'Professional Golfers Career College',
  'Carrington College-Pleasant Hill',
  'Shasta Bible College and Graduate School',
  'Azusa Pacific University',
  'Allan Hancock College',
  'Fresno City College',
  'Fullerton College',
  'Argosy University-The Art Institute of California-San Diego',
  'Los Angeles Valley College',
  'Mt San Antonio College',
  'Oxnard College',
  'Concorde Career College-San Diego',
  'Modesto Junior College',
  'Brightwood College-Vista',
  'Palomar College',
  'Pasadena City College',
  'Santa Barbara Business College-Santa Maria',
  'Point Loma Nazarene University',
  'Santa Monica College',
  'Southwestern College',
  'Santa Ana College',
  'San Francisco State University',
  'University of San Francisco',
  'Taft College',
  'Yuba College',
  'West Los Angeles College',
  'Academy of Art University',
  'Biola University',
  'College of Alameda',
  'American Academy of Dramatic Arts-Los Angeles',
  'American Career College-Los Angeles',
  'Antelope Valley College',
  'California Polytechnic State University-San Luis Obispo',
  'Chabot College',
  'Cosumnes River College',
  'Crafton Hills College',
  'Cypress College',
  'California State University-Dominguez Hills',
  'California State University-Los Angeles',
  'California State University-Sacramento',
  'University of California-Los Angeles',
  'East Los Angeles College',
  'Laguna College of Art and Design',
  'Fashion Institute of Design & Merchandising-Los Angeles',
  'Marymount California University',
  'Los Angeles City College',
  'Los Angeles County College of Nursing and Allied Health',
  'Argosy University-The Art Institute of California-San Francisco',
  'Scripps College',
  'Victor Valley College',
  'Los Angeles ORT College-Van Nuys Campus',
  'Mt Sierra College'];


var schoolTest = ['John Paul the Great Catholic University',
  'Advanced Computing Institute',
  'California Miramar University' ];

var resultArray = [];

var getMeAllImages = function(image) {
  resultArray.push(image);
  console.log(resultArray);
};

for (var i = 339; i < 347; i++) {
  sleep.sleep(1);

  console.log(i);
  
  Bing.images(schoolNames[i], {count: 1 }, function (error, res, body) {
    getMeAllImages(body.value[0].thumbnailUrl);
  });

  
}
console.log(schoolNames.length);







